server:
  error:
    include-stacktrace: on_param
  port: 8080
  address: 0.0.0.0

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/anime?createDatabaseIfNotExist=true
    password: root
    username: root
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus

info:
  app: Spring Boot Essentials
  website: https://www.linkedin.com/in/joaovictor0101
  github: https://github.com/juaovictor0101/springboot-essentials