server:
  error:
    include-stacktrace: on_param

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/anime?createDatabaseIfNotExist=true
    password: root
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true